services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:5000"
    volumes:
      - .:/app:rw
    command: flask run --host=0.0.0.0 --port=5000
    env_file:
      - .env
    depends_on:
      - db
    read_only: true
    mem_limit: 512m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend

  db:
    image: postgres:13
    env_file:
      - .env
    read_only: true
    mem_limit: 512m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    networks:
      - backend

networks:
  frontend:
  backend:
