version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5

  flask-app:
    build: ./flask-app
    environment:
      FLASK_ENV: development
      KEYCLOAK_REALM: master-realm
      KEYCLOAK_CLIENT_ID: flask-client
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/master-realm
    depends_on:
      - keycloak
    ports:
      - "5000:5000"

